### ISSUE TITLE
input file issue

### ISSUE THREAD

**Issue by zuodabin** [DyogenIBENS/Agora#17]
Hello and thank you for your software Agora. Now I want to run the software, but I don't know how to get the other two input files besides the species tree. Can you tell me how to get it? Thank you

**Comment by alouis72** [comment]
Hi, 
thank you for your interest in AGORA.
I'm not sure I understand your question. 
If you want to run the AGORA software to reconstruct ancestral gene order among a species tree, you will have to compute and format yourself all the data needed (gene trees, gene positions) by using or building a pipeline of comparative genomics that suits your interests.
There are many comparative genomics pipeline available in the literature (Ensembl-compara, OrthoFinder, etc...) for that. Otherwise, if your genomes of interest are already in public comparative genomic database (Ensembl, OMA, ...), there are tools available (such as API described on the corresponding web interface) to download what you need to process it.
Hope this helps.

Alex

**Comment by zuodabin** [comment]
Hi, AGORA needs three input files, I already have the species tree (through OrthoFinder), how should I prepare the other two files?
Best wishes
